### ISSUE TITLE
Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by teod** [andreypopp/react-textarea-autosize#210]
I get an error after updating to the 7.0.1 version from 6.0.0:
```
Uncaught TypeError: callback is not a function
    at TextareaAutosize._this._resizeComponent
```

**Comment by Andarist** [comment]
Please upgrade to 7.0.2 - it should be fixed in it.
