### ISSUE TITLE
callback is not a function (number passed instead)

### ISSUE THREAD

**Issue by lufego** [andreypopp/react-textarea-autosize#208]
After update to 7.0.1, I receive the following console error:

![image](https://user-images.githubusercontent.com/14938754/42503336-b34e794c-8438-11e8-885e-46cf72f38c4c.png)

````js
_this._resizeComponent = function (callback) {
      if (callback === void 0) {
        callback = noop;
      }

      var nodeHeight = calculateNodeHeight(_this._ref, _this._uid, _this.props.useCacheForDOMMeasurements, _this.props.minRows, _this.props.maxRows);

      if (nodeHeight === null) {
        callback();
        return;
      }

      var height = nodeHeight.height,
          minHeight = nodeHeight.minHeight,
          maxHeight = nodeHeight.maxHeight,
          rowCount = nodeHeight.rowCount,
          valueRowCount = nodeHeight.valueRowCount;
      _this.rowCount = rowCount;
      _this.valueRowCount = valueRowCount;

      if (_this.state.height !== height || _this.state.minHeight !== minHeight || _this.state.maxHeight !== maxHeight) {
        _this.setState({
          height: height,
          minHeight: minHeight,
          maxHeight: maxHeight
        }, callback);

        return;
      }

      callback();
    };
````

Something is passing a number as a callback. I didn't investigate yet tho

**Comment by Andarist** [comment]
Should be fixed by 7.0.2. Feel free to open a new issue if the problem persists

**Comment by lufego** [comment]
Thanks for the quick fix @Andarist
